name: Docker Image CI for shopify-tracker
on:
  push:
    branches: [ master ]

permissions: read-all

jobs:
  build:
    name: Test and build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get image version
        id: get-version
        run: |
          VERSION=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/^release\///;s/^hotfix-release\///')
          echo $VERSION          
          echo "::set-output name=version::$VERSION"

     
      - name: Build the Docker image and push
        run: |
          docker build -f Dockerfile -t rudderstack/rudder-shopify-tracker:${{steps.get-version.outputs.version}} .
      - name: Push the image to Dockerhub
        run: |
          docker push rudderstack/rudder-shopify-tracker:${{steps.get-version.outputs.version}}