name: Deploy shopify-tracker to staging environment
on:
  workflow_call:
    inputs:
      image_tag:
        type: string
        required: true
        description: docker image which needs to be deployed to staging environment
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      PAT:
        required: true
        description: Personal access token to be used for cloning rudder-devops

permissions: read-all

jobs:
  prepare-staging-image-tag:
    runs-on: ubuntu-latest
    outputs:
      tag_name_stg: "staging-${{inputs.image_tag}}"

  build-push-staging-image:
    needs: [prepare-staging-image-tag]
    uses: ./.github/workflows/build-and-push-docker-image.yml
    with:
      img_tag: ${{ needs.prepare-staging-image-tag.outputs.tag_name_stg }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: [prepare-staging-image-tag, build-push-staging-image]
    steps:
      - name: Initialize Mandatory Git Config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"

      - name: Clone Devops Repo
        run: |
          git clone https://${{secrets.PAT}}@github.com/rudderlabs/rudder-devops.git

      - name: Create staging PR
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          SP_IMAGE_REPOSITORY: rudderstack/rudder-shopify-tracker
          TAG_NAME: ${{needs.prepare-staging-image-tag.outputs.tag_name_stg}}
        run: |
          cd rudder-devops
          git checkout -b shopify-tracker-$TAG_NAME $TAG_NAME
          cd helm-charts/helm/shopify-tracking/environment/staging
          yq eval -i ".image.tag=\"$TAG_NAME\"" base.yaml
          yq eval -i ".image.repository=\"$SP_IMAGE_REPOSITORY\"" base.yaml
          git add base.yaml
          git commit -m "chore: upgrade shopify tracker to $TAG_NAME"
          git push -u origin shopify-tracker-$TAG_NAME
          gh pr create --fill